
spring:
  #环境dev/test/pro
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


# Mybatis配置
mybatis:
  config-location: classpath:mybatis.xml
  # mapper映射文件地址，这里我在src/main/resouces下新建文件夹mapper
  mapper-locations: classpath*:mapper/**/*.xml
  # 配置bean扫描目录，也可用注解
      #type-aliases-package: classpath*:com.example.demo.entity


logging:
  level:
  # 日志配置，打印sql语句
     com.example.myproject.dao : debug